resources:
- name: bats
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-cpi
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-cpi.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-cpi-release
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-cpi-release.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-private
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-private.git
    branch: master
    private_key: {{private-repo-key}}

- name: bosh-softlayer-stemcells
  type: git
  source:
    uri: git@github.com:maximilien/bosh-softlayer-stemcells.git
    branch: bosh-cli-docker
    private_key: {{private-repo-key}}

- name: bosh-stemcell-softlayer-image
  type: s3
  source:
    bucket: bosh-softlayer-cpi-stemcells
    regexp: bosh-stemcell-softlayer.vhd
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: final-release
  type: s3
  source:
    bucket: bosh-softlayer-cpi-stemcells
    regexp: bosh-softlayer-cpi-release-(.*).tgz
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: softlayer-go
  type: git
  source:
    uri: git@github.com:maximilien/softlayer-go.git
    branch: master
    private_key: {{private-repo-key}}

- name: version
  type: semver
  source:
    bucket: bosh-softlayer-cpi-stemcells
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0

- name: softlayer-stemcell
  type: s3
  source:
    bucket: bosh-softlayer-cpi-stemcells
    regexp: bosh-stemcell-(.*)-vsphere-(.*).tgz
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: stemcell-info
  type: s3
  source:
    bucket: bosh-softlayer-cpi-stemcells
    versioned_file: stemcell-info.json
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: vsphere-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

jobs:
- name: bats
  serial: true
  plan:
  - aggregate:
    - get: bats
    - get: bosh-softlayer-cpi
    - get: bosh-softlayer-cpi-release
    - get: bosh-softlayer-stemcells
  - task: test
    file: bosh-softlayer-stemcells/ci/bats.yml
    config:
      params:
        NETWORK_GATEWAY: {{NETWORK_GATEWAY}}
        SL_VLAN: {{SL_VLAN}}

- name: bosh-stemcell
  plan:
  - aggregate:
    - get: bosh
    - get: bosh-softlayer-stemcells
    - get: bosh-softlayer-private
    - get: vsphere-stemcell
      trigger: true
  - task: bosh-stemcell
    file: bosh-softlayer-stemcells/ci/bosh-stemcell.yml
    config:
      params:
        BOSH_AWS_ACCESS_KEY_ID: {{BOSH_AWS_ACCESS_KEY_ID}}
        BOSH_AWS_SECRET_ACCESS_KEY: {{BOSH_AWS_SECRET_ACCESS_KEY}}
        BOSH_KEY_PATH: ../../bosh-softlayer-private/bosh.pem
        AWS_ACCESS_KEY: {{BOSH_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY: {{BOSH_AWS_SECRET_ACCESS_KEY}}
        S3_ACCESS_KEY: {{s3-access-key-id}}
        S3_SECRET_KEY: {{s3-secret-access-key}}

- name: convert-stemcell
  plan:
  - get: bosh-softlayer-stemcells
    trigger: true
  - get: bosh-softlayer-stemcells
    trigger: true
    passed: [bosh-stemcell]
  - task: convert-stemcell
    file: bosh-softlayer-stemcells/ci/convert-stemcell.yml
    config:
      params:
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_API_KEY:  {{SL_API_KEY}}
        SWIFT_CLUSTER:  {{SWIFT_CLUSTER}}
        S3_ACCESS_KEY:  {{s3-access-key-id}}
        S3_SECRET_KEY:  {{s3-secret-access-key}}

- name: cpi-unit
  public: true
  plan:
  - get: bosh-softlayer-cpi
    trigger: true
  - task: unit
    file: bosh-softlayer-cpi/ci/unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key

- name: cpi-integration
  plan:
  - get: bosh-softlayer-cpi
    trigger: true
    passed: [cpi-unit]
  - task: build
    file: bosh-softlayer-cpi/ci/build.yml
  - task: integration
    file: bosh-softlayer-cpi/ci/integration.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}

- name: cpi-build
  plan:
  - get: bosh-softlayer-cpi
    trigger: true
    passed: [cpi-integration]
  - task: build
    file: bosh-softlayer-cpi/ci/build.yml

- name: cpi-release-rc
  serial: true
  plan:
  - get: bosh-softlayer-cpi-release
    trigger: true
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/number}

- name: cpi-release-shipit
  serial: true
  plan:
  - aggregate:
    - get: bosh-softlayer-private
    - get: bosh-softlayer-cpi-release
      passed: [cpi-release-rc]
    - get: version
      passed: [cpi-release-rc]
      params: {bump: final}
  - task: create-final-release
    file: bosh-softlayer-cpi-release/ci/shipit.yml
    config:
      params:
        S3_ACCESS_KEY: {{s3-access-key-id}}
        S3_SECRET_KEY: {{s3-secret-access-key}}
  - aggregate:  
    - put: final-release
      params: {from: create-final-release/bosh-softlayer-cpi-release-.*.tgz}
    - put: version
      params: {file: version/number}

- name: create-light-stemcell
  plan:
  - aggregate:
    - get: bosh-softlayer-stemcells
      passed: [import-stemcell]
    - get: stemcell-info
      trigger: true
      passed: [import-stemcell]
  - task: create-light-stemcell
    file: bosh-softlayer-stemcells/ci/create-light-stemcell.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}
        S3_ACCESS_KEY: {{s3-access-key-id}}
        S3_SECRET_KEY: {{s3-secret-access-key}}

- name: remove-expiration-tag
  plan:
  - get: stemcell-info
    trigger: true
    passed: import-stemcell
  - task: remove-expiration-tag-vhd
    file: bosh-softlayer-stemcells/ci/remove-expiration.yml
    config:
      params:
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_API_KEY:  {{SL_API_KEY}}
        SWIFT_CLUSTER:  {{SWIFT_CLUSTER}}
        S3_ACCESS_KEY:  {{s3-access-key-id}}
        S3_SECRET_KEY:  {{s3-secret-access-key}}

- name: import-stemcell
  plan:
  - get: bosh-softlayer-stemcells
    trigger: true
    passed: [convert-stemcell]
  - task: import-stemcell-image
    file: bosh-softlayer-stemcells/ci/import-stemcell.yml
    config:
      params:
        SL_USERNAME:    {{SL_USERNAME}}
        SL_API_KEY:     {{SL_API_KEY}}
        SWIFT_USERNAME: {{SWIFT_USERNAME}}
        SWIFT_CLUSTER:  {{SWIFT_CLUSTER}}
        S3_ACCESS_KEY:  {{s3-access-key-id}}
        S3_SECRET_KEY:  {{s3-secret-access-key}}
  - put: stemcell-info
    params: {from: import-stemcell-image/stemcell-info.json}

- name: stemcells-unit
  public: true
  plan:
  - get: bosh-softlayer-stemcells
    trigger: true
  - task: unit
    file: bosh-softlayer-stemcells/ci/unit.yml

- name: sl-go-unit
  public: true
  plan:
  - get: softlayer-go
    trigger: true
  - task: unit
    file: softlayer-go/ci/unit.yml
    config:
      params:
        SL_USERNAME: fake-username
        SL_API_KEY: fake-api-key

- name: sl-go-integration
  plan:
  - get: softlayer-go
    trigger: true
    passed: [sl-go-unit]
  - task: integration
    file: softlayer-go/ci/integration.yml
    config:
      params:
        SL_USERNAME: {{SL_USERNAME}}
        SL_API_KEY: {{SL_API_KEY}}


groups:
- name: all
  jobs:
  - bats
  - bosh-stemcell
  - convert-stemcell
  - create-light-stemcell
  - cpi-unit
  - cpi-integration
  - cpi-build
  - cpi-release-rc
  - cpi-release-shipit
  - import-stemcell
  - stemcells-unit
  - sl-go-unit
  - sl-go-integration

- name: bosh-softlayer-cpi
  jobs:
  - cpi-unit
  - cpi-integration
  - cpi-build

- name: bosh-softlayer-cpi-release
  jobs:
  - cpi-release-rc
  - cpi-release-shipit

- name: bosh-softlayer-stemcells
  jobs:
  - bosh-stemcell
  - convert-stemcell
  - create-light-stemcell
  - import-stemcell
  - stemcells-unit

- name: softlayer-go
  jobs:
  - sl-go-unit
  - sl-go-integration