---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: bosh-softlayer-tools-master
  - name: bosh-softlayer-tools
  - name: stemcell-info
  - name: version
  - name: stemcell
  - name: stemcell-cmds
outputs:
  - name: light-stemcell

run:
  path: bosh-softlayer-tools-master/ci/softlayer/tasks/create-light-stemcell.sh

params:
  HYPERVISOR:       replace-me
  IAAS:             replace-me
  OS_NAME:          replace-me
  OS_VERSION:       replace-me
  STEMCELL_FORMATS: replace-me
  SL_USERNAME:      replace-me
  SL_API_KEY:       replace-me
