---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh

inputs:
  - name: stemcell-version
  - name: bosh-softlayer-tools
  - name: stemcell-ubuntu-trusty-raw
outputs:
  - name: build
run:
  path: bosh-softlayer-tools/ci/tasks/generate-bm-stemcell-fsa.sh
