#!/bin/bash

(
  set -e

  echo -e "\n Set env vars..."
  INFRASTRUCTURE=softlayer
  HYPERVISOR=esxi
  OS_NAME=ubuntu
  OS_VERSION=trusty
  NETWORK_TYPE=dynamic
  AGENT_TYPE=go
  LIGHT_STEMCELL_FLAG=true
  DISK_FORMAT=raw

  echo -e "\n Install vagrant plugins..."
  vagrant plugin install vagrant-berkshelf
  vagrant plugin install vagrant-omnibus
  vagrant plugin install vagrant-aws --plugin-version 0.5.0

  echo -e "\n Navigate to vagrant directory..."
  cd bosh/bosh-stemcell

  echo -e "\n Copy s3cfg to vagrant shared directory..."
  cp ../../bosh-softlayer-private/.s3cfg .

  echo -e "\n Bring up vagrant stemcell building VM for AWS EC2-Classic..."
  vagrant up remote --provider=aws

  echo -e "\n Build stemcell, then upload to S3 bucket..."
  vagrant ssh -c "
    cd /bosh
    s3cmd get s3://bosh-softlayer-cpi-stemcells/light-bosh-stemcell-0000-softlayer-esxi-ubuntu-trusty-go_agent.tgz /bosh/tmp/light-bosh-stemcell-0000-softlayer-esxi-ubuntu-trusty-go_agent.tgz -c /vagrant/.s3cfg
    bundle exec rake spec:system:micro[${INFRASTRUCTURE},${HYPERVISOR},${OS_NAME},${OS_VERSION},${NETWORK_TYPE},${AGENT_TYPE},${LIGHT_STEMCELL_FLAG},${DISK_FORMAT}]
  " remote

  echo -e "\n Terminating VM"
  ec2-describe-instances --filter "key-name=bosh" | grep instance | awk '{print $3}' | xargs ec2-terminate-instances
)
