#!/bin/bash

(
  set -e

  echo -e "\n Get stemcell version..."
  STEMCELL_VERSION=`cat vsphere-stemcell/version`
  echo $STEMCELL_VERSION > stemcell-version
  s3cmd put stemcell-version s3://bosh-softlayer-cpi-stemcells --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY

  echo -e "\n Install vagrant plugins..."
  vagrant plugin install vagrant-berkshelf
  vagrant plugin install vagrant-omnibus
  vagrant plugin install vagrant-aws --plugin-version 0.5.0

  echo -e "\n Navigate to vagrant directory..."
  cd bosh/bosh-stemcell

  echo -e "\n Copy s3cfg to vagrant shared directory..."
  cp ../../bosh-softlayer-private/.s3cfg .

  echo -e "\n Bring up vagrant stemcell building VM for AWS EC2-Classic..."
  vagrant up remote --provider=aws

  echo -e "\n Build stemcell, then upload to S3 bucket..."
  vagrant ssh -c "
    cd /bosh
    CANDIDATE_BUILD_NUMBER=${STEMCELL_VERSION} bundle exec rake stemcell:build[vsphere,esxi,ubuntu,trusty,go,bosh-os-images,bosh-ubuntu-trusty-os-image.tgz]
    s3cmd put /bosh/tmp/*.tgz s3://bosh-softlayer-cpi-stemcells -c /vagrant/.s3cfg
  " remote

  echo -e "\n Terminating VM"
  ec2-describe-instances --filter "key-name=bosh" | grep instance | awk '{print $3}' | xargs ec2-terminate-instances
)
