#!/bin/bash

(
  set -e

  echo -e "\n Get stemcell version..."
  STEMCELL_VERSION=`cat vsphere-stemcell/version`

  echo -e "\n /etc/init.d/vboxdrv setup or update linux-headers..."
  sudo /etc/init.d/vboxdrv setup

  echo -e "\n Install vagrant plugins..."
  vagrant plugin install vagrant-berkshelf
  vagrant plugin install vagrant-omnibus
  vagrant plugin install vagrant-aws --plugin-version 0.5.0

  echo -e "\n Updating with fresh copy of bosh repo, probably unnecessary..."
  cd bosh
  git submodule update --init --recursive

  echo -e "\n Navigate to vagrant directory..."
  cd bosh-stemcell

  echo -e "\n Copy s3cfg to vagrant shared directory..."
  cp ../../bosh-softlayer-private/.s3cfg .

  echo -e "\n Bring up vagrant stemcell building VM for AWS EC2-Classic..."
  vagrant up remote --provider=aws

  echo -e "\n Update source code on stemcell building VM..."
  vagrant provision remote

  echo -e "\n Build stemcell, then upload to S3 bucket..."
  vagrant ssh -c "
    cd /bosh
    CANDIDATE_BUILD_NUMBER=${STEMCELL_VERSION} bundle exec rake stemcell:build[vsphere,esxi,ubuntu,trusty,go,bosh-os-images,bosh-ubuntu-trusty-os-image.tgz]
    s3cmd put /tmp/*.tgz s3://bosh-softlayer-cpi-stemcells -c /vagrant/.s3cfg
  " remote

  echo -e "\n Terminating VM"
  vagrant destroy
)
