#!/bin/bash

(
  set -e

  echo -e "\n Print PWD and contents..."
  echo $PWD
  ls

  echo -e "\n Get stemcell version..."
  STEMCELL_VERSION=`cat vsphere-stemcell/version`

  echo -e "\n Install vagrant plugins..."
  vagrant plugin install vagrant-berkshelf
  vagrant plugin install vagrant-omnibus
  vagrant plugin install vagrant-aws --plugin-version 0.5.0

  # echo -e "\n Fresh copy of bosh repo, probably unnecessary..."
  # cd bosh
  # git submodule update --init --recursive

  # echo -e "\n Copying $ID_RSA_BOSH /root/.ssh/id_rsa_bosh"
  # mv ../bosh-softlayer-private/id_rsa_bosh bosh-stemcell

  echo -e "\n Bring up vagrant stemcell building VM for AWS EC2-Classic..."
  cd bosh/bosh-stemcell
  vagrant up remote --provider=aws

  # echo -e "\n Update source code on stemcell building VM..."
  # vagrant provision remote

  echo -e "\n Build stemcell..."
  vagrant ssh -c '
    cd /bosh
    CANDIDATE_BUILD_NUMBER=${STEMCELL_VERSION} bundle exec rake stemcell:build[vsphere,esxi,ubuntu,trusty,go,bosh-os-images,bosh-ubuntu-trusty-os-image.tgz]
    s3cmd put /tmp/*.tgz s3://bosh-softlayer-cpi-stemcells --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY
  ' remote
)
