#!/bin/bash

(
  set -e

  echo -e "\n Unpacking tgz..."
  find softlayer-stemcell -name "*.tgz" -exec tar zxf '{}' \;

  echo -e "\n Converting vmdk to vhd"
  VBoxManage clonehd image --format VHD bosh-stemcell-softlayer.vhd
)
