#!/bin/bash

(
  set -e

  echo -e "\n Printing contents of directory..."
  ls

  echo -e "\n Unpacking tgz..."
  find softlayer-stemcell -name "bosh-stemcell-*-vsphere-*.tgz" -exec tar zxf '{}' \;
  tar zxf image

  echo -e "\n Converting vmdk to vhd..."
  VBoxManage clonehd *.vmdk --format VHD bosh-stemcell-softlayer.vhd

  echo -e "\n Placing object in Softlayer..."
  chmod +x ObjectStorageUploader.sh
  ./ObjectStorageUploader.sh *.vhd 'stemcells/bosh-stemcell-softlayer.vhd' $swift-username $swift-apikey
)
