#!/bin/bash

(
  set -e

  base=$( cd "$( dirname "$( dirname "$( dirname "$0" )")")" && pwd )
  base_gopath=$( cd $base/../../../.. && pwd )

  export GOPATH=$base/Godeps/_workspace:$base_gopath:$GOPATH

  echo -e "\n Print $base and $base_gopath and $PWD..."
  echo $base
  echo $base_gopath
  echo $PWD

  echo -e "\n Creating stemcell binary..."
  go build -o out/sl_stemcells github.com/maximilien/bosh-softlayer-stemcells/main

  echo -e "\n Softlayer create light stemcell..."
  out/sl_stemcells --version 3061 --stemcell-info-filename stemcell-info/stemcell-info.json light-stemcell
)