#!/bin/bash

(
  set -e

  base=$( cd "$( dirname "$( dirname "$( dirname "$0" )")")" && pwd )
  base_gopath=$( cd $base/../../../.. && pwd )
  
  echo -e "\n Print base..."
  echo $base

  export GOPATH=$base/Godeps/_workspace:$base_gopath:$GOPATH

  echo -e "\n Print contents of current dir..."
  ls

  echo -e "\n Creating stemcell binary..."
  go build -o out/sl_stemcells github.com/maximilien/bosh-softlayer-stemcells/main

  echo -e "\n Softlayer create from external source..."
  IFS=':' read -ra OBJ_STORAGE_ACC_NAME <<< "$SWIFT_USERNAME"
  URI="swift://${OBJ_STORAGE_ACC_NAME}@${SWIFT_CLUSTER}/stemcells/bosh-stemcell-softlayer.vhd"
  out/sl_stemcells --os-ref-code UBUNTU_14_64 --uri ${URI} import-image | tail -1 >> stemcell-info.json
)