#!/usr/bin/env bash

set -e

source bosh-softlayer-stemcells/ci/scripts/utils.sh

print_git_state bosh-softlayer-cpi-release

check_param base_os
check_param BAT_NETWORKING
check_param SL_VLAN
check_param NETWORK_CIDR
check_param NETWORK_GATEWAY
check_param BATS_DIRECTOR_IP
check_param BATS_STEMCELL_NAME
check_param BATS_IP1
check_param BATS_IP2
check_param BATS_RESERVED_RANGE1
check_param BATS_RESERVED_RANGE2
check_param BATS_STATIC_RANGE

source /etc/profile.d/chruby-with-ruby-2.1.2.sh

echo "using bosh CLI version..."
bosh version
bosh -n target $BATS_DIRECTOR_IP

echo -e "\n Get stemcell version..."
s3cmd get s3://bosh-softlayer-cpi-stemcells/stemcell-version stemcell-version --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY
STEMCELL_VERSION=`cat stemcell-version`

echo -e "\n Get stemcell..."
s3cmd get s3://bosh-softlayer-cpi-stemcells/light-bosh-stemcell-${STEMCELL_VERSION}-vsphere-esxi-ubuntu-trusty-go_agent.tgz stemcell.tgz --access_key=$S3_ACCESS_KEY --secret_key=$S3_SECRET_KEY

export BAT_INFRASTRUCTURE=softlayer
export BAT_VCAP_PASSWORD=c1oudc0w
export BAT_DNS_HOST=$BATS_DIRECTOR_IP
export BAT_DIRECTOR=$BATS_DIRECTOR_IP
export BAT_STEMCELL="${PWD}/stemcell.tgz"
export BAT_DEPLOYMENT_SPEC="${PWD}/${base_os}-${BAT_NETWORKING}-bats-config.yml"

cat > $BAT_DEPLOYMENT_SPEC <<EOF
---
cpi: vcloud
properties:
  uuid: $(bosh status --uuid)
  second_static_ip: ${BATS_IP2}
  pool_size: 1
  stemcell:
    name: ${BATS_STEMCELL_NAME}
    version: latest
  instances: 1
  networks:
    - name: static
      static_ip: ${BATS_IP1}
      type: manual
      cidr: ${NETWORK_CIDR}
      reserved:
        - ${BATS_RESERVED_RANGE1}
        - ${BATS_RESERVED_RANGE2}
      static: [${BATS_STATIC_RANGE}]
      gateway: ${NETWORK_GATEWAY}
      vlan: ${SL_VLAN}
  vapp_name: bats-concourse-${base_os}-vapp
EOF

ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa

cd bats
bundle install
bundle exec rspec spec
