#!/bin/bash

(
  set -x

  base=$( cd "$( dirname "$( dirname "$( dirname "$0" )")")" && pwd )
  base_gopath=$( cd $base/../../../.. && pwd )

  export GOPATH=$base/Godeps/_workspace:$base_gopath:$GOPATH

  echo -e "\n Get stemcell version..."
  STEMCELL_VERSION=$(cat stemcell-version/number | sed 's/\.0$//;s/\.0$//')

  echo -e "\n Creating stemcell binary..."
  cd "${base}"
  go build -o out/sl_stemcells main/stemcells/stemcells.go

  echo -e "\n Softlayer create light stemcell..."
  out/sl_stemcells -c light-stemcell --version $STEMCELL_VERSION --stemcell-info-filename "${base_gopath}/../stemcell-info/stemcell-info.json"

  cp *.tgz "${base_gopath}/../new-light-stemcell/"
)