#!/bin/bash

(
  set -x

  base=$( cd "$( dirname "$( dirname "$( dirname "$0" )")")" && pwd )
  base_gopath=$( cd $base/../../../.. && pwd )

  export GOPATH=$base/Godeps/_workspace:$base_gopath:$GOPATH

  echo -e "\n Get stemcell version..."
  STEMCELL_VERSION=$(cat stemcell-version/number | sed 's/\.0$//;s/\.0$//')

  echo -e "\n Creating stemcell binary..."
  cd "${base}"
  go build -o out/sl_stemcells main/stemcells/stemcells.go

  echo -e "\n Softlayer create from external source..."
  IFS=':' read -ra OBJ_STORAGE_ACC_NAME <<< "$SWIFT_USERNAME"
  URI="swift://${OBJ_STORAGE_ACC_NAME}@${SWIFT_CLUSTER}/${SWIFT_CONTAINER}/bosh-stemcell-${STEMCELL_VERSION}-softlayer.vhd"
  out/sl_stemcells -c import-image --os-ref-code UBUNTU_14_64 --uri ${URI} --public-name "light-bosh-stemcell-${STEMCELL_VERSION}-softlayer-esxi-ubuntu-trusty-go_agent" \
      --public-note "Public_light_stemcell_${STEMCELL_VERSION}" --public | tail -1 >> "${base_gopath}/../stemcell-image/stemcell-info.json"
)