---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: zhanggongsw/bosh
    
inputs:
  - name: published-stemcell
  - name: bosh-softlayer-tools
outputs:
  - name: version
run:
  path: bosh-softlayer-tools/ci/tasks/make-stemcell-version.sh
