---
platform: linux
image: docker:///boshcpi/azure-cpi-release

inputs:
- name: bosh-cli-v2
- name: bosh-softlayer-tools

outputs:
- name: deploy-artifacts

run:
  path: bosh-softlayer-tools/ci/tasks/create-env-automation/deploy-director-v2.sh

params:
  SL_VM_PREFIX:         replace-me
  SL_API_KEY:           replace-me
  SL_DATACENTER:        replace-me
  SL_VLAN_PUBLIC:       replace-me
  SL_VLAN_PRIVATE:      replace-me
