resources:
- name: bosh-softlayer-tools
  type: git
  source:
    uri: https://github.com/zhanggbj/bosh-softlayer-tools.git
    branch: WIP-security

- name: light-stemcell
  type: s3
  source:
    regexp: light-bosh-stemcell-([0-9.]+)-softlayer-xen-ubuntu-trusty-go_agent\.tgz
    bucket: {{s3_bluemix_stemcell_bucket}}
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

jobs:
- name: upgrade-environment
  public: true
  plan:
  - aggregate:
      - {trigger: false, get: stemcell, resource: light-stemcell}
      - {trigger: false, get: bosh-softlayer-tools, resource: bosh-softlayer-tools}

  - task: upgrade-environment
    file: bosh-softlayer-tools/ci/tasks/upgrade-environment.yml
    config:
      params:
        DEPLOYMENT_YML: {{deployment_yml}}
        BLUEMIX_DIRECTOR_IP: {{bluemix_director_ip}}
        BOSH_CLI: {{bosh_cli}}
        BOSH_CLI_PASSWORD: {{bosh_cli_password}}
    on_success:
        task: post-upgrade
        file: bosh-softlayer-tools/ci/tasks/post-upgrade.yml
        config:
          params:
            DEPLOYMENT_YML: {{deployment_yml}}
            BLUEMIX_DIRECTOR_IP: {{bluemix_director_ip}}
            BOSH_CLI: {{bosh_cli}}
            BOSH_CLI_PASSWORD: {{bosh_cli_password}}
    on_failure:
        task: restore-environment
        file: bosh-softlayer-tools/ci/tasks/restore-environment.yml
        config:
          params:
            DEPLOYMENT_YML: {{deployment_yml}}
            BLUEMIX_DIRECTOR_IP: {{bluemix_director_ip}}
            BOSH_CLI: {{bosh_cli}}
            BOSH_CLI_PASSWORD: {{bosh_cli_password}}

- name: verify-security-release
  public: true
  plan:
  - aggregate:
      - {trigger: false, passed: [upgrade-environment], get: bosh-softlayer-tools, resource: bosh-softlayer-tools}

  - task: verify-security-release
    file: bosh-softlayer-tools/ci/tasks/verify-security-release.yml
    config:
      params:
        BLUEMIX_DIRECTOR_IP: {{bluemix_director_ip}}
        BOSH_CLI: {{bosh_cli}}
        BOSH_CLI_PASSWORD: {{bosh_cli_password}}

- name: verify-environment
  public: true
  plan:
  - aggregate:
      - {trigger: false, passed: [verify-security-release], get: bosh-softlayer-tools, resource: bosh-softlayer-tools}

  - task: cf-push-app
    file: bosh-softlayer-tools/ci/tasks/verify-environment.yml
    config:
      params:
          CF-API:                 {{cf-api}}
          CF-USERNAME:            {{cf-username}}
          CF-PASSWORD:            {{cf-password}}
          APP-API:                {{app-api}}
          NAME_SERVER:            {{name-server}}