---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/azure-cpi-release

inputs:
  - name: stemcell
  - name: bosh-softlayer-tools
  - name: bats
  - name: deployment
  - name: stemcell-version
outputs:
  - name: final-stemcell
run:
  path: bosh-softlayer-tools/ci/tasks/run-bats.sh
params:
  BASE_OS:                      replace-me
  BAT_VCAP_PASSWORD:            replace-me
  BAT_SECOND_STATIC_IP:         replace-me
  BAT_NETWORK_STATIC_IP:        replace-me
  BAT_NETWORK_CIDR:             replace-me
  BAT_NETWORK_RESERVED_RANGE:   replace-me
  BAT_NETWORK_STATIC_RANGE:     replace-me
  BAT_NETWORK_GATEWAY:          replace-me
  SL_DATACENTER:                replace-me
  SL_VLAN_PUBLIC:               replace-me
  SL_VLAN_PRIVATE:              replace-me
  SL_VM_NAME_PREFIX:            replace-me
  SL_VM_DOMAIN:                 softlayer.com


