---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/azure-cpi-release
inputs:
  - name: bosh-cpi-artifacts # -++ used for deployment manifest referenced by manifest_path
  - name: bosh-softlayer-tools
  - name: bosh-init              # --- bosh-init executable to do deploy
  - name: bosh-release           # -\
  - name: stemcell
outputs:
  - name: deployment
run:
  path: bosh-softlayer-tools/ci/tasks/setup-director.sh
params:
  BASE_OS:                    replace-me
  SL_USERNAME:                replace-me
  SL_API_KEY:                 replace-me
  SL_DATACENTER:              replace-me
  SL_VLAN_PUBLIC:             replace-me
  SL_VLAN_PRIVATE:            replace-me
  SL_VM_NAME_PREFIX:          replace-me
  SL_VM_DOMAIN:               softlayer.com
  BOSH_INIT_LOG_LEVEL:        warn